echo 'Editing The Environment to Your Preferences...'
echo 'Moving Window Buttons To The Left...'
gsettings set org.gnome.desktop.wm.preferences button-layout 'close,maximize,minimize:'
echo 'Putting Important Apps on the Dock...'
echo 'NOTE: The Above Feature is Not Implimented Yet.'